checkpoints_every: 24
data_type: TOP-10_CLM
fix_seed: 0
use_plinder_dataset: false
max_pos_weight: 1
use_positive_weighting_for_binding_sites: true
model:
  backbone_dropout_rate: 0.3
  classifier_dropout_rate: 0.5
  last_state_dropout_rate: 0.0
  freeze_backbone: true
  num_unfrozen_layers: 3 #3
  freeze_embeddings: true
  hidden_size: 1280
  model_name: facebook/esm2_t33_650M_UR50D
  structure_aware: true
  dtype: "bfloat16"
  # chemical encoder configs
  use_chemical_encoder: true
  chemical_encoder_num_unfrozen_layers: 3
  clm_max_length: 128 # TODO - experiment
  clm_output_dim: 768
  clm_hidden_dropout_rate: 0.1
  clm_embedding_dropout_rate: 0.0

num_ligands: 10
optimizer:
  beta_1: 0.9
  beta_2: 0.999
  decay:
    gamma: 0.2
    min_lr: 0
    num_restarts: 1
    warmup: 512
  eps: 1e-16
  grad_clip_norm: 1
  lr: 5e-5
  momentum: 0.9
  name: adam
  nesterov: true
  use_8bit_adam: false
  weight_decay: 1e-2
  weight_decouple: true
pos_weight_divisor: 30
result_path: ./results/test/
scheduler:
  T_0: 24
  T_max: 24
  T_mult: 2
  eta_min: 0
  eta_min_first: 0.0005
  eta_min_second: 1.0e-05
  name: cosine_annealing
tensorboard_log: true
test_settings:
  batch_size: 16
  num_workers: 4
  test_label_path: ./data/Y01/test_labels.fasta
  test_seq_path: ./data/Y01/test_set.fasta
tqdm_progress_bar: true
train_settings:
  alpha: 0.9
  batch_size: 16
  gamma: 1
  grad_accumulation: 4
  grad_clip_norm: 1
  label_smoothing: 0.0
  max_sequence_length: 768 #768
  mixed_precision: bf16
  num_epochs: 24
  num_workers: 4
  shuffle: true
  train_label_path: ./data/Y01/train_labels.fasta
  train_seq_path: ./data/Y01/train_set.fasta
transformer_head:
  num_heads: 8
  num_layers: 4
  dim_feedforward: 2048
  dropout: 0.3
valid_settings:
  batch_size: 64
  num_workers: 4
  valid_label_path: ./data/Y01/eval_labels.fasta
  valid_seq_path: ./data/Y01/eval_set.fasta
data_root: "./data"
noise_std: 0.00 # experimental results show 0.05 works best
mask_prob: 0.00 # 0.15
mask_token_id: 32
ligands:
  - ADP
  - ATP
  - CA
  - CLA
  - FAD
  - HEM
  - MG
  - NAD
  - NAP
  - ZN
dataset_weight: # square rooted weights
  # For BIOLIP
  ACO: 6.572248051043451
  ADP: 2.226542617996696
  AGS: 5.856745733616519
  AMP: 4.1186935263061715
  ANP: 3.6301468429933954
  ATP: 2.6192163174596823
  BGC: 3.7541517802459543
  BMA: 5.4337203144527235
  CA: 1.238154521240631
  CLA: 3.6932845648816426
  CLR: 5.148366907882714
  CO: 5.399652766613794
  COA: 4.244005538590049
  CU: 3.7541517802459543
  FAD: 2.377928816122437
  FE: 2.961215458638767
  FE2: 5.008058022955637
  FES: 4.1413446239256215
  FMN: 3.267270605297025
  GAL: 4.474534526346602
  GDP: 3.7095905362860004
  GLC: 3.205515621000118
  GSH: 4.8295962564173
  GTP: 5.576737397439475
  HEC: 4.203623977647685
  HEM: 2.349619130661733
  MAN: 3.234136864080644
  MG: 1.257306669431238
  MN: 2.431573056380809
  NAD: 2.6626426071659415
  NAP: 3.1776410428811177
  NDP: 4.3814987006956345
  PLP: 3.517670437241071
  PO4: 3.513014352556767
  SAH: 3.449711611726643
  SAM: 4.668946928436942
  SF4: 3.0273799678183995
  SO4: 4.625914241402162
  UDP: 5.503835734486249
  Y01: 6.633960654259577
  ZN: 1.0
dataset_weight_plinder:
  # For PLINDER
  ADP: 1.2817
  ATP: 1.4135
  CA: 2.7592
  CLA: 3.8928
  FAD: 1.542
  HEM: 1.0
  MG: 1.0515
  NAD: 1.4876
  NAP: 1.6737
  ZN: 2.1242

pos_dataset_weight:
  # For BIOLIP, square rooted
  ACO: 4.6176
  ADP: 7.0186
  AGS: 6.9843
  AMP: 6.4685
  ANP: 6.7729
  ATP: 7.7615
  BGC: 7.6696
  BMA: 10.0504
  CA: 7.2932
  CLA: 2.1068
  CLR: 9.325
  CO: 8.3624
  COA: 5.3376
  CU: 8.4515
  FAD: 4.6984
  FE: 8.5749
  FE2: 9.759
  FES: 6.5512
  FMN: 5.0443
  GAL: 7.8087
  GDP: 5.6888
  GLC: 7.4536
  GSH: 5.5132
  GTP: 5.7166
  HEC: 3.0387
  HEM: 4.4065
  MAN: 9.0167
  MG: 11.547
  MN: 9.4072
  NAD: 4.6778
  NAP: 4.4901
  NDP: 4.4811
  PLP: 6.5938
  PO4: 8.2479
  SAH: 5.3
  SAM: 5.1367
  SF4: 6.1314
  SO4: 7.2357
  UDP: 6.2994
  Y01: 8.3045
  ZN: 8.6387

pos_dataset_weight_plinder:
    # For PLINDER, square rooted
    ADP: 11.47
    ATP: 12.29
    CA: 15.17
    CLA: 13.71
    FAD: 8.75
    HEM: 5.9
    MG: 19.69
    NAD: 8.08
    NAP: 6.86
    ZN: 12.42

ligand_to_smiles:
  ACO: "CC(=O)SCCNC(=O)CCNC(=O)[C@@H](C(C)(C)CO[P@](=O)(O)O[P@@](=O)(O)OC[C@@H]1[C@H]([C@H]([C@@H](O1)n2cnc3c2ncnc3N)O)OP(=O)(O)O"
  ADP: "c1nc(c2c(n1)n(cn2)[C@H]3[C@@H]([C@@H]([C@H](O3)CO[P@](=O)(O)OP(=O)(O)O)O)O)N"
  AGS: "c1nc(c2c(n1)n(cn2)[C@H]3[C@@H]([C@@H]([C@H](O3)COP(=O)(O)OP(=O)(O)OP(=S)(O)O)O)O)N"
  AMP: "c1nc(c2c(n1)n(cn2)[C@H]3[C@@H]([C@@H]([C@H](O3)COP(=O)(O)O)O)O)N"
  ANP: "c1nc(c2c(n1)n(cn2)[C@H]3[C@@H]([C@@H]([C@H](O3)CO[P@](=O)(O)O[P@@](=O)(NP(=O)(O)O)O)O)O)N"
  ATP: "c1nc(c2c(n1)n(cn2)[C@H]3[C@@H]([C@@H]([C@H](O3)CO[P@@](=O)(O)O[P@](=O)(O)OP(=O)(O)O)O)O)N"
  BGC: "C([C@@H]1[C@H]([C@@H]([C@H]([C@@H](O1)O)O)O)O)O"
  BMA: "C([C@@H]1[C@H]([C@@H]([C@@H]([C@@H](O1)O)O)O)O)O"
  CA: "[Ca+2]"
  CLA: "CCC1=C(C2=Cc3c(c(c4n3[Mg]56[N]2=C1C=C7N5C8=C([C@H](C(=O)C8=C7C)C(=O)OC)C9=[N]6C(=C4)[C@H]([C@@H]9CCC(=O)OC/C=C(\\C)/CCC[C@H](C)CCC[C@H](C)CCCC(C)C)C)C)C=C)C"
  CLR: "CC(C)CCC[C@@H](C)[C@H]1CC[C@@H]2[C@@]1(CC[C@H]3[C@H]2CC=C4[C@@]3(CC[C@@H](C4)O)C)"
  CO: "[Co+2]"
  COA: "CC(C)(CO[P@](=O)(O)O[P@@](=O)(O)OC[C@@H]1[C@H]([C@H]([C@@H](O1)n2cnc3c2ncnc3N)O)OP(=O)(O)O)[C@H](C(=O)NCCC(=O)NCCS)O"
  CU: "[Cu+2]"
  FAD: "Cc1cc2c(cc1C)N(C3=NC(=O)NC(=O)C3=N2)C[C@@H]([C@@H]([C@@H](CO[P@@](=O)(O)O[P@](=O)(O)OC[C@@H]4[C@H]([C@H]([C@@H](O4)n5cnc6c5ncnc6N)O)O)O)O)O"
  FE: "[Fe+3]"
  FE2: "[Fe+2]"
  FES: "S1[Fe]S[Fe]1"
  FMN: "Cc1cc2c(cc1C)N(C3=NC(=O)NC(=O)C3=N2)C[C@@H]([C@@H]([C@@H](COP(=O)(O)O)O)O)O"
  GAL: "C([C@@H]1[C@@H]([C@@H]([C@H]([C@@H](O1)O)O)O)O)O"
  GDP: "c1nc2c(n1[C@H]3[C@@H]([C@@H]([C@H](O3)CO[P@](=O)(O)OP(=O)(O)O)O)O)N=C(NC2=O)N"
  GLC: "C([C@@H]1[C@H]([C@@H]([C@H]([C@H](O1)O)O)O)O)O"
  GSH: "C(CC(=O)N[C@@H](CS)C(=O)NCC(=O)O)[C@@H](C(=O)O)N"
  GTP: "c1nc2c(n1[C@H]3[C@@H]([C@@H]([C@H](O3)CO[P@](=O)(O)O[P@](=O)(O)OP(=O)(O)O)O)O)N=C(NC2=O)N"
  HEC: "CC=C1C(=C2C=C3C(=CC)C(=C4N3[Fe]56N2C1=Cc7n5c(c(c7C)CCC(=O)O)C=C8N6C(=C4)C(=C8CCC(=O)O)C)"
  HEM: "Cc1c2n3c(c1CCC(=O)O)C=C4C(=C(C5=[N]4[Fe]36[N]7=C(C=C8N6C(=C5)C(=C8C)C=C)C(=C(C7=C2)C)C=C)C)CCC(=O)O"
  MAN: "C([C@@H]1[C@H]([C@@H]([C@@H]([C@H](O1)O)O)O)O)O"
  MG: "[Mg+2]"
  MN: "[Mn+2]"
  NAD: "c1cc(c[n+](c1)[C@H]2[C@@H]([C@@H]([C@H](O2)CO[P@@](=O)([O-])O[P@@](=O)(O)OC[C@@H]3[C@H]([C@H]([C@@H](O3)n4cnc5c4ncnc5N)O)O)O)O)C(=O)N"
  NAP: "c1cc(c[n+](c1)[C@H]2[C@@H]([C@@H]([C@H](O2)CO[P@@](=O)([O-])O[P@](=O)(O)OC[C@@H]3[C@H]([C@H]([C@@H](O3)n4cnc5c4ncnc5N)OP(=O)(O)O)O)O)O)C(=O)N"
  NDP: "c1nc(c2c(n1)n(cn2)[C@H]3[C@@H]([C@@H]([C@H](O3)CO[P@](=O)(O)O[P@@](=O)(O)OC[C@@H]4[C@H]([C@H]([C@@H](O4)N5C=CCC(=C5)C(=O)N)O)O)O)OP(=O)(O)O)N"
  PLP: "Cc1c(c(c(cn1)COP(=O)(O)O)C=O)O"
  PO4: "[O-]P(=O)([O-])[O-]"
  SAH: "c1nc(c2c(n1)n(cn2)[C@H]3[C@@H]([C@@H]([C@H](O3)CSCC[C@@H](C(=O)O)N)O)O)N"
  SAM: "C[S@@+](CC[C@@H](C(=O)[O-])N)C[C@@H]1[C@H]([C@H]([C@@H](O1)n2cnc3c2ncnc3N)O)O"
  SF4: "[S]12[Fe]3[S]4[Fe]1[S]5[Fe]2[S]3[Fe]45"
  SO4: "[O-]S(=O)(=O)[O-]"
  UDP: "C1=CN(C(=O)NC1=O)[C@H]2[C@@H]([C@@H]([C@H](O2)CO[P@@](=O)(O)OP(=O)(O)O)O)O"
  Y01: "CC(C)CCC[C@@H](C)[C@H]1CC[C@@H]2[C@@]1(CC[C@H]3[C@H]2CC=C4[C@@]3(CC[C@@H](C4)OC(=O)CCC(=O)O)C)"
  ZN: "[Zn+2]"