checkpoints_every: 24
data_type: TOP-10
fix_seed: 0
ligand_embedding_size: 480
max_pos_weight: 1
model:
  backbone_dropout_rate: 0.3
  classifier_dropout_rate: 0.5
  freeze_backbone: true
  freeze_backbone_layers: 30
  freeze_embeddings: true
  hidden_size: 1280
  model_name: facebook/esm2_t33_650M_UR50D
num_ligands: 10
optimizer:
  beta_1: 0.9
  beta_2: 0.999
  decay:
    gamma: 0.2
    min_lr: 0
    num_restarts: 1
    warmup: 512
  eps: 1e-16
  grad_clip_norm: 1
  lr: 5e-5
  momentum: 0.9
  name: adam
  nesterov: true
  use_8bit_adam: false
  weight_decay: 1e-2
  weight_decouple: true
pos_weight_divisor: 30
result_path: ./results/test/
scheduler:
  T_0: 24
  T_max: 24
  T_mult: 2
  eta_min: 0
  eta_min_first: 0.0005
  eta_min_second: 1.0e-05
  name: cosine_annealing
tensorboard_log: true
test_settings:
  batch_size: 16
  num_workers: 4
  test_label_path: ./data/Y01/test_labels.fasta
  test_seq_path: ./data/Y01/test_set.fasta
tqdm_progress_bar: true
train_settings:
  alpha: 0.9
  batch_size: 16
  gamma: 1
  grad_accumulation: 4
  grad_clip_norm: 1
  label_smoothing: 0.0
  max_sequence_length: 768
  mixed_precision: bf16
  num_epochs: 24
  num_workers: 4
  shuffle: true
  train_label_path: ./data/Y01/train_labels.fasta
  train_seq_path: ./data/Y01/train_set.fasta
transformer_head:
  num_heads: 8
  num_layers: 4
  dim_feedforward: 2048
  dropout: 0.0
valid_settings:
  batch_size: 16
  num_workers: 4
  valid_label_path: ./data/Y01/eval_labels.fasta
  valid_seq_path: ./data/Y01/eval_set.fasta
data_root: "./data"
ligands:
  - ADP
  - ATP
  - CA
  - CLA
  - FAD
  - HEM
  - MG
  - NAD
  - NAP
  - ZN

