# =========================
# USER SETTINGS (edit these)
# =========================
input_csv_path: "./data/example_data.csv" # Path to your input CSV file
output_csv_path: "./data/output.csv" # Path to save output predictions
checkpoint_path: "./placeholder_checkpoint.pth" # Path to your checkpoint
stage_3: true # Set to true if using Stage 3 checkpoint, false if using Stage 2 checkpoint
batch_size: 8
prediction_threshold: 0.5 # Set the cutoff for positive binding classification
device_type: "cuda" # Options: cuda, cpu
use_mixed_precision: true
mixed_precision_dtype: "bfloat16" # Supported options: bfloat16, float32
lig_name_col: "ligand_name" # Modify if your file uses different headers
prot_seq_col: "protein_sequence"
smiles_col: "SMILES" # Only required for Stage 3 checkpoints
sequence_length: 1024 # Context length for protein sequences
output_binding_probs: true # If true, outputs a full list of binding probabilities for each residue in the output csv

# =========================
# MODEL SETTINGS
# =========================
model:
  cache_dir: "./hf_cache"
  use_compile: false
  backbone_dropout_rate: 0.3
  classifier_dropout_rate: 0.5
  last_state_dropout_rate: 0.0
  freeze_backbone: true
  num_unfrozen_layers: 0
  freeze_embeddings: true
  hidden_size: 1280
  model_name: "facebook/esm2_t33_650M_UR50D"
  structure_aware: false
  use_chemical_encoder: true
  chemical_encoder_source: "huggingface"
  huggingface_model_name: "ibm-research/MoLFormer-XL-both-10pct"
  chemical_encoder_num_unfrozen_layers: 0
  unfreeze_clm_embeddings: false
  clm_max_length: 128
  clm_output_dim: 768
  clm_hidden_dropout_rate: 0.3
  clm_embedding_dropout_rate: 0.0
use_dynamic_SMILES: true
num_ligands: 166 # Only for Stage 2
optimizer:
  beta_1: 0.9
  beta_2: 0.98
  decay:
    gamma: 0.2
    min_lr: 0
    num_restarts: 1
    warmup: 512
  eps: 1e-7
  grad_clip_norm: 1
  lr: 5e-5
  momentum: 0.9
  name: adam
  nesterov: true
  use_8bit_adam: false
  weight_decay: 1e-2
  weight_decouple: true
scheduler:
  T_0: 24
  T_max: 24
  T_mult: 2
  eta_min: 0
  eta_min_first: 0.0005
  eta_min_second: 1.0e-05
  name: cosine_annealing
tqdm_progress_bar: true
transformer_head:
  num_heads: 8
  num_layers: 4
  dim_feedforward: 2048
  dropout: 0.3
